# Generated by Django 5.2.12 on 2026-04-02 07:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipdNo', models.CharField(blank=True, max_length=50, unique=True)),
                ('admNo', models.PositiveIntegerField()),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_location', models.CharField(choices=[('LNM', 'Laxmi Nagar'), ('RYM', 'Raya')], default='LNM', max_length=3)),
                ('uhid', models.CharField(blank=True, max_length=25, unique=True)),
                ('patientName', models.CharField(max_length=150)),
                ('guardianName', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=15)),
                ('dob', models.DateField(blank=True, null=True)),
                ('bloodGroup', models.CharField(blank=True, max_length=10)),
                ('maritalStatus', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('altPhone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('nationalId', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('payMode', models.CharField(default='cash', max_length=20)),
                ('cashlessType', models.CharField(blank=True, max_length=20)),
                ('tpa', models.CharField(blank=True, max_length=100)),
                ('tpaCard', models.CharField(blank=True, max_length=50)),
                ('tpaValidity', models.DateField(blank=True, null=True)),
                ('tpaCardType', models.CharField(blank=True, max_length=50)),
                ('tpaPanelCardNo', models.CharField(blank=True, max_length=50)),
                ('tpaPanelValidity', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ICU CARE', 'ICU Care'), ('ROOM CHARGE', 'Room Charge'), ('CONSULTANT', 'Consultant'), ('RADIOLOGY', 'Radiology'), ('GENERAL SERVICES', 'General Services')], max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentMode', models.CharField(blank=True, max_length=50)),
                ('paidNow', models.BooleanField(default=False)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='patients.admission')),
            ],
        ),
        migrations.CreateModel(
            name='Discharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expectedDod', models.DateField(blank=True, null=True)),
                ('dod', models.DateTimeField(blank=True, null=True)),
                ('dischargeStatus', models.CharField(blank=True, max_length=100)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discharge', to='patients.admission')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previousDiagnosis', models.TextField(blank=True)),
                ('pastSurgeries', models.TextField(blank=True)),
                ('currentMedications', models.TextField(blank=True)),
                ('treatingDoctor', models.CharField(blank=True, max_length=150)),
                ('knownAllergies', models.TextField(blank=True)),
                ('chronicConditions', models.TextField(blank=True)),
                ('familyHistory', models.TextField(blank=True)),
                ('smokingStatus', models.CharField(blank=True, max_length=50)),
                ('alcoholUse', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medicalHistory', to='patients.admission')),
            ],
        ),
        migrations.AddField(
            model_name='admission',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='patients.patient'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svcName', models.CharField(max_length=200)),
                ('svcCat', models.CharField(blank=True, max_length=100)),
                ('svcDate', models.DateField(blank=True, null=True)),
                ('svcQty', models.PositiveIntegerField(default=1)),
                ('svcRate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('svcTot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='patients.admission')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='admission',
            unique_together={('patient', 'admNo')},
        ),
    ]
