# Generated by Django 5.2.12 on 2026-04-22 12:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipdNo', models.CharField(blank=True, max_length=50, unique=True)),
                ('admNo', models.PositiveIntegerField()),
                ('admissionType', models.CharField(choices=[('IPD', 'IPD'), ('OPD', 'OPD'), ('DayCare', 'Day Care')], default='IPD', max_length=20)),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_location', models.CharField(choices=[('LNM', 'Laxmi Nagar'), ('RYM', 'Raya')], default='LNM', max_length=3)),
                ('uhid', models.CharField(blank=True, max_length=25, unique=True)),
                ('patientName', models.CharField(max_length=150)),
                ('guardianName', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=15)),
                ('dob', models.DateField(blank=True, null=True)),
                ('bloodGroup', models.CharField(blank=True, max_length=10)),
                ('maritalStatus', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('altPhone', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField()),
                ('nationalId', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('payMode', models.CharField(default='cash', max_length=20)),
                ('cashlessType', models.CharField(blank=True, max_length=20)),
                ('tpa', models.CharField(blank=True, max_length=100)),
                ('tpaCard', models.CharField(blank=True, max_length=50)),
                ('tpaValidity', models.DateField(blank=True, null=True)),
                ('tpaCardType', models.CharField(blank=True, max_length=50)),
                ('tpaPanelCardNo', models.CharField(blank=True, max_length=50)),
                ('tpaPanelValidity', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ICU CARE', 'ICU Care'), ('ROOM CHARGE', 'Room Charge'), ('CONSULTANT', 'Consultant'), ('RADIOLOGY', 'Radiology'), ('GENERAL SERVICES', 'General Services')], max_length=50)),
                ('pricing_type', models.CharField(choices=[('CASH', 'Cash'), ('CASHLESS', 'Cashless')], default='CASH', max_length=10)),
                ('description', models.TextField()),
                ('code', models.CharField(blank=True, max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_type', models.CharField(choices=[('CASH', 'Cash'), ('CASHLESS', 'Cashless')], default='CASH', max_length=20)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('advance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remarks', models.TextField(blank=True)),
                ('paymentMode', models.CharField(blank=True, max_length=50)),
                ('paidNow', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('printStatus', models.CharField(default='DRAFT', max_length=50)),
                ('printRequestedAt', models.DateTimeField(blank=True, null=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='patients.admission')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('opd', 'OPD'), ('intimation', 'Intimation'), ('query', 'Query'), ('uploading', 'Uploading')], max_length=20)),
                ('branch', models.CharField(choices=[('LNM', 'Laxmi Nagar'), ('RYM', 'Raya')], default='LNM', max_length=10)),
                ('record_date', models.DateField()),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_logs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-record_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Discharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=100)),
                ('doctorName', models.CharField(blank=True, max_length=150)),
                ('wardName', models.CharField(blank=True, max_length=100)),
                ('roomNo', models.CharField(blank=True, max_length=50)),
                ('bedNo', models.CharField(blank=True, max_length=50)),
                ('diagnosis', models.TextField(blank=True)),
                ('doa', models.DateTimeField(blank=True, null=True)),
                ('expectedDod', models.DateField(blank=True, null=True)),
                ('dod', models.DateTimeField(blank=True, null=True)),
                ('dischargeStatus', models.CharField(blank=True, max_length=100)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discharge', to='patients.admission')),
            ],
        ),
        migrations.CreateModel(
            name='DischargeSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_type', models.CharField(choices=[('NORMAL', 'Normal'), ('LAMA', 'LAMA'), ('REFERRED', 'Referred'), ('DEATH', 'Death'), ('DOPR', 'dopr')], max_length=20)),
                ('content', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dynamic_summary', to='patients.admission')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HODReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('period', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('performance_score', models.CharField(blank=True, max_length=100)),
                ('comments', models.TextField(blank=True)),
                ('task_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hod_reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_hod_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previousDiagnosis', models.TextField(blank=True)),
                ('pastSurgeries', models.TextField(blank=True)),
                ('currentMedications', models.TextField(blank=True)),
                ('treatingDoctor', models.CharField(blank=True, max_length=150)),
                ('knownAllergies', models.TextField(blank=True)),
                ('chronicConditions', models.TextField(blank=True)),
                ('familyHistory', models.TextField(blank=True)),
                ('smokingStatus', models.CharField(blank=True, max_length=50)),
                ('alcoholUse', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medicalHistory', to='patients.admission')),
            ],
        ),
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_name', models.CharField(max_length=255)),
                ('table_data', models.JSONField(default=list)),
                ('text_data', models.JSONField(blank=True, default=list)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to='patients.admission')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to='patients.patient')),
            ],
        ),
        migrations.AddField(
            model_name='admission',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='patients.patient'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_applied', models.CharField(default='CASH', max_length=10)),
                ('svcName', models.CharField(max_length=200)),
                ('svcCat', models.CharField(blank=True, max_length=100)),
                ('svcDate', models.DateField(blank=True, null=True)),
                ('svcQty', models.PositiveIntegerField(default=1)),
                ('svcRate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('svcTot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='patients.admission')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('department', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Urgent', 'Urgent')], default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Overdue', 'Overdue')], default='Pending', max_length=20)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_given', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_received', to=settings.AUTH_USER_MODEL)),
                ('patients', models.ManyToManyField(related_name='assigned_tasks', to='patients.patient')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='admission',
            unique_together={('patient', 'admNo')},
        ),
    ]
