# Generated by Django 5.2.12 on 2026-04-03 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='printRequestedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='printStatus',
            field=models.CharField(default='DRAFT', max_length=50),
        ),
    ]
