# Generated by Django 5.2.12 on 2026-03-28 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='aadhaar_number',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='altPhone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='patient',
            name='bloodGroup',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='patient',
            name='branch_location',
            field=models.CharField(choices=[('LNM', 'Laxmi Nagar'), ('RYM', 'Raya')], default='LNM', max_length=3),
        ),
        migrations.AddField(
            model_name='patient',
            name='cashlessType',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='patient',
            name='guardianName',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='maritalStatus',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='nationalId',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='patientName',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='payMode',
            field=models.CharField(default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='tpa',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='patient',
            name='tpaCard',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='tpaCardType',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='tpaPanelCardNo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='tpaPanelValidity',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='tpaValidity',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='uhid',
            field=models.CharField(blank=True, max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(max_length=15),
        ),
    ]
