# Generated by Django 5.2.12 on 2026-04-17 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_dischargesummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='bill_type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CASHLESS', 'Cashless')], default='CASH', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='pricing_applied',
            field=models.CharField(default='CASH', max_length=10),
        ),
        migrations.AddField(
            model_name='servicemaster',
            name='pricing_type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('CASHLESS', 'Cashless')], default='CASH', max_length=10),
        ),
        migrations.AlterField(
            model_name='billing',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='patients.admission'),
        ),
    ]
