# Generated by Django 5.2.12 on 2026-04-01 05:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_remove_patient_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admNo', models.PositiveIntegerField()),
                ('dateTime', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='patients.patient')),
            ],
            options={
                'unique_together': {('patient', 'admNo')},
            },
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentMode', models.CharField(blank=True, max_length=50)),
                ('paidNow', models.BooleanField(default=False)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='patients.admission')),
            ],
        ),
        migrations.CreateModel(
            name='Discharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expectedDod', models.DateField(blank=True, null=True)),
                ('dod', models.DateTimeField(blank=True, null=True)),
                ('dischargeStatus', models.CharField(blank=True, max_length=100)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='discharge', to='patients.admission')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previousDiagnosis', models.TextField(blank=True)),
                ('pastSurgeries', models.TextField(blank=True)),
                ('currentMedications', models.TextField(blank=True)),
                ('treatingDoctor', models.CharField(blank=True, max_length=150)),
                ('knownAllergies', models.TextField(blank=True)),
                ('chronicConditions', models.TextField(blank=True)),
                ('familyHistory', models.TextField(blank=True)),
                ('smokingStatus', models.CharField(blank=True, max_length=50)),
                ('alcoholUse', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medicalHistory', to='patients.admission')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svcName', models.CharField(max_length=200)),
                ('svcCat', models.CharField(blank=True, max_length=100)),
                ('svcDate', models.DateField(blank=True, null=True)),
                ('svcQty', models.PositiveIntegerField(default=1)),
                ('svcRate', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('svcTot', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='patients.admission')),
            ],
        ),
    ]
