# Generated by Django 5.2.12 on 2026-04-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_billing_printrequestedat_billing_printstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='discharge',
            name='bedNo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='discharge',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='discharge',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='discharge',
            name='doa',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discharge',
            name='doctorName',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='discharge',
            name='roomNo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='discharge',
            name='wardName',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
