# Generated by Django 5.2.12 on 2026-04-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_medicinemaster_reportmaster_pharmacyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='insuranceType',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='billing',
            name='tpaDocStatus',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='billing',
            name='tpaInfo',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='discharge',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='discharge',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='labreport',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='labreport',
            name='modality_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='labreport',
            name='ordered_by',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='labreport',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='labreport',
            name='report_category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='labreport',
            name='report_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labreport',
            name='report_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
