# Generated by Django 5.2.12 on 2026-04-27 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_medicinemaster_reportmaster_pharmacyrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='patients',
        ),
        migrations.AddField(
            model_name='task',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='patients.patient'),
        ),
    ]
