# Generated by Django 5.2.12 on 2026-04-27 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_billing_insurancetype_billing_tpadocstatus_and_more'),
        ('patients', '0003_remove_task_patients_task_patient'),
    ]

    operations = [
    ]
