# Generated by Django 5.2.12 on 2026-04-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_admission_billing_discharge_medicalhistory_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ICU CARE', 'ICU Care'), ('ROOM CHARGE', 'Room Charge'), ('CONSULTANT', 'Consultant'), ('RADIOLOGY', 'Radiology'), ('GENERAL SERVICES', 'General Services')], max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=50)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
