# Generated by Django 5.2.12 on 2026-04-22 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_labreport_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='admissionType',
            field=models.CharField(choices=[('IPD', 'IPD'), ('OPD', 'OPD'), ('DayCare', 'Day Care')], default='IPD', max_length=20),
        ),
        migrations.AddField(
            model_name='billing',
            name='advance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='billing',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='billing',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    ALTER TABLE patients_billing ALTER COLUMN "paidNow" DROP DEFAULT;
                    ALTER TABLE patients_billing
                    ALTER COLUMN "paidNow" TYPE numeric(10, 2)
                    USING CASE WHEN "paidNow" IS TRUE THEN 1.00 ELSE 0.00 END;
                    ALTER TABLE patients_billing ALTER COLUMN "paidNow" SET DEFAULT 0;
                    """,
                    reverse_sql="""
                    ALTER TABLE patients_billing ALTER COLUMN "paidNow" DROP DEFAULT;
                    ALTER TABLE patients_billing
                    ALTER COLUMN "paidNow" TYPE boolean
                    USING CASE WHEN COALESCE("paidNow", 0) <> 0 THEN TRUE ELSE FALSE END;
                    ALTER TABLE patients_billing ALTER COLUMN "paidNow" SET DEFAULT FALSE;
                    """,
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='billing',
                    name='paidNow',
                    field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('opd', 'OPD'), ('intimation', 'Intimation'), ('query', 'Query'), ('uploading', 'Uploading')], max_length=20)),
                ('branch', models.CharField(choices=[('LNM', 'Laxmi Nagar'), ('RYM', 'Raya')], default='LNM', max_length=10)),
                ('record_date', models.DateField()),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_logs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-record_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HODReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('period', models.CharField(choices=[('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=20)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('performance_score', models.CharField(blank=True, max_length=100)),
                ('comments', models.TextField(blank=True)),
                ('task_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hod_reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_hod_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(
                choices=[
                    ('Pending', 'Pending'),
                    ('In Progress', 'In Progress'),
                    ('Completed', 'Completed'),
                    ('On Hold', 'On Hold'),
                    ('Overdue', 'Overdue'),
                ],
                default='Pending',
                max_length=20,
            ),
        ),
    ]
