# Generated by Django 5.2.12 on 2026-05-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_dynamic_branch_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='branch_location',
            field=models.CharField(default='LNM', max_length=10),
        ),
    ]
