# Generated by Django 5.2.12 on 2026-05-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0014_alter_patient_branch_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalhistory',
            name='chiefComplaints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='customList',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='pr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='presentComplaints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='provisionalDiagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalhistory',
            name='treatmentAdvised',
            field=models.TextField(blank=True, null=True),
        ),
    ]
