# Generated by Django 5.2.12 on 2026-05-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_add_missing_medicalhistory_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='svcCode',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='payMode',
            field=models.CharField(max_length=20),
        ),
    ]
