# Generated by Django 5.2.12 on 2026-05-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_service_svccode_alter_patient_paymode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='svcCode',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
