# Generated by Django 5.2.12 on 2026-04-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Branch Admin'), ('office_admin', 'Office Admin'), ('receptionist', 'Receptionist'), ('billing', 'Billing Staff')], default='receptionist', max_length=20),
        ),
    ]
