# Generated by Django 5.2.12 on 2026-04-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Branch Admin'), ('office_admin', 'Office Admin'), ('receptionist', 'Receptionist'), ('billing', 'Billing'), ('hod', 'HOD'), ('opd', 'OPD'), ('intimation', 'Intimation'), ('query', 'Query'), ('uploading', 'Uploading')], default='receptionist', max_length=20),
        ),
    ]
